import { Flex } from "@chakra-ui/react";

export default function Myimg({ bgi }) {
  return (
    <>
      <Flex gap="30px" my="30px">
        <Flex
          backgroundImage={bgi}
          bgColor="#1b1b1b"
          backgroundPosition="center"
          backgroundSize="cover"
          w="350px"
          h="350px"
          rounded={16}
        />
        <Flex
          backgroundImage={bgi}
          bgColor="#1b1b1b"
          backgroundPosition="center"
          backgroundSize="cover"
          w="350px"
          h="350px"
          rounded={16}
        />
        <Flex
          backgroundImage={bgi}
          bgColor="#1b1b1b"
          backgroundPosition="center"
          backgroundSize="cover"
          w="350px"
          h="350px"
          rounded={16}
        />
      </Flex>
      <Flex gap="30px">
        <Flex
          backgroundImage={bgi}
          bgColor="#1b1b1b"
          backgroundPosition="center"
          backgroundSize="cover"
          w="350px"
          h="350px"
          rounded={16}
        />
        <Flex
          backgroundImage={bgi}
          bgColor="#1b1b1b"
          backgroundPosition="center"
          backgroundSize="cover"
          w="350px"
          h="350px"
          rounded={16}
        />
        <Flex
          backgroundImage={bgi}
          bgColor="#1b1b1b"
          backgroundPosition="center"
          backgroundSize="cover"
          w="350px"
          h="350px"
          rounded={16}
        />
      </Flex>
      <Flex gap="30px" my="30px">
        <Flex
          backgroundImage={bgi}
          bgColor="#1b1b1b"
          backgroundPosition="center"
          backgroundSize="cover"
          w="350px"
          h="350px"
          rounded={16}
        />
        <Flex
          backgroundImage={bgi}
          bgColor="#1b1b1b"
          backgroundPosition="center"
          backgroundSize="cover"
          w="350px"
          h="350px"
          rounded={16}
        />
        <Flex
          backgroundImage={bgi}
          bgColor="#1b1b1b"
          backgroundPosition="center"
          backgroundSize="cover"
          w="350px"
          h="350px"
          rounded={16}
        />
      </Flex>
      <Flex gap="30px">
        <Flex
          backgroundImage={bgi}
          bgColor="#1b1b1b"
          backgroundPosition="center"
          backgroundSize="cover"
          w="350px"
          h="350px"
          rounded={16}
        />
        <Flex
          backgroundImage={bgi}
          bgColor="#1b1b1b"
          backgroundPosition="center"
          backgroundSize="cover"
          w="350px"
          h="350px"
          rounded={16}
        />
        <Flex
          backgroundImage={bgi}
          bgColor="#1b1b1b"
          backgroundPosition="center"
          backgroundSize="cover"
          w="350px"
          h="350px"
          rounded={16}
        />
      </Flex>
    </>
  );
}
