import Head from "next/head";

import Navbar from "../components/Navbar";
import MyGrid from "../components/MyGrid";
import Layout from "../components/Bg/LtLayout";
import MyHeader from "../components/Header/MyHeader";
import { Divider, Flex, GridItem } from "@chakra-ui/react";
import MyMain from "../components/Main/MyMain";
import MyBg from "../components/Main/MyBg";
import MyWork from "../components/Main work/MyWork";
import MyMission from "../components/Main mission/MainM";
import Myimg from "../components/Main work/Myimg";

export default function Home() {
  return (
    <>
      <Head>
        <title>LND - Lukas Nerozi Design</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;700;800;900&display=swap"
          rel="stylesheet"
        />
      </Head>

      <Layout>
        <MyGrid background="linear-gradient(180deg, rgba(21, 21, 21, 0) 77.6%, #151515 100%), url(bg1.png)">
          <GridItem colStart={[1, 1, 1, 1]} colSpan={[5, 6, 4, 4]}>
            <MyHeader />
          </GridItem>

          <GridItem colStart={[1, 1, 1, 1]} colSpan={[5, 8, 12, 12]}>
            <MyMain />
          </GridItem>

          <GridItem colStart={[1, 1, 1, 1]} colSpan={[5, 8, 12, 12]}>
            <MyMission />
          </GridItem>
          <GridItem colStart={[1, 1, 1, 1]} colSpan={[5, 8, 12, 12]} mt="170px">
            <MyWork />
          </GridItem>
          <GridItem colStart={[1, 1, 1, 1]} colSpan={[5, 8, 12, 12]}>
            <Myimg />
          </GridItem>
        </MyGrid>
        <MyBg />
      </Layout>
    </>
  );
}
